element asked for challenge 2
RozkeAdine/DonkeySchool pull request #2
Opened 2022-05-24 12:04 UTC by RozkeAdine

2022-05-24 12:18 UTC, Sarawilong requested changes
Indentation à revoir

2022-05-24 12:18 UTC, Sarawilong commented on CSS/style.css
> +
useless line

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +                <H3>projet 1</H3>
Majuscule

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +            <divc id="projet_2">
divc?

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +                <H3>projet 3</H3>
Majuscule

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +            </div>
cs

2022-05-24 12:18 UTC, Sarawilong commented on index.html
nothing in there ?

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +                <H3>article 1</H3>
majuscule

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +
useless line

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +                <input type="text" value="">
id de l'input where is it ?

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +                <input type="email" value="@">
same here

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +                  <button type="submit">envoyer</button>
Majuscule

2022-05-24 12:18 UTC, Sarawilong commented on index.html
> +                  <button type="submit">envoyer</button>
cs

2022-05-24 12:18 UTC, Sarawilong commented on index.html
useless line

2022-05-25 11:48 UTC, RozkeAdine commented
Hello
Sarawi,

Je me suis rendu compte de la majorité des fautes dont tu parles hier soir pendant que je travaillais encore sur le portfolio : j’aurais dû mieux vérifier mon code !!
Input : je ne savais pas qu’il lui fallait un id aussi.

Je te tiens au courant

Cordialement.

Le 24 mai 2022 à 14:18, Sarawilong ***@***.***> a écrit :

﻿

@Sarawilong requested changes on this pull request.

Indentation à revoir

________________________________

In CSS/style.css<https://github.com/RozkeAdine/DonkeySchool/pull/2#discussion_r880424885>:

> @@ -0,0 +1,10 @@
+#projet_global{
+    width: 100%;
+


useless line

________________________________

In index.html<https://github.com/RozkeAdine/DonkeySchool/pull/2#discussion_r880426760>:

>          </header>
     <section>

-           <article>
-        <h2>titre 2</h2>
-        <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=">
-    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
-    et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+           <article id="projet_global">
+        <h2>Projet Réalisés</h2>
+            <div id="projet_1">
+                <H3>projet 1</H3>


Majuscule

________________________________

In index.html<https://github.com/RozkeAdine/DonkeySchool/pull/2#discussion_r880427096>:

>          </header>
     <section>

-           <article>
-        <h2>titre 2</h2>
-        <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=">
-    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
-    et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+           <article id="projet_global">
+        <h2>Projet Réalisés</h2>
+            <div id="projet_1">
+                <H3>projet 1</H3>
+                <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=" height="100" widht="470" alt="chateau en foret1">
+                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
+                et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+            </div>
+            <divc id="projet_2">


divc?

________________________________

In index.html<https://github.com/RozkeAdine/DonkeySchool/pull/2#discussion_r880427347>:

> +           <article id="projet_global">
+        <h2>Projet Réalisés</h2>
+            <div id="projet_1">
+                <H3>projet 1</H3>
+                <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=" height="100" widht="470" alt="chateau en foret1">
+                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
+                et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+            </div>
+            <divc id="projet_2">
+                <H3>projet 2</H3>
+                <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=" height="100" widht="470" alt="chateau en foret1">
+                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
+                et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+            </divc>
+            <div id="projet_3">
+                <H3>projet 3</H3>


Majuscule

________________________________

In index.html<https://github.com/RozkeAdine/DonkeySchool/pull/2#discussion_r880427532>:

> +                <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=" height="100" widht="470" alt="chateau en foret1">
+                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
+                et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+            </div>
+            <divc id="projet_2">
+                <H3>projet 2</H3>
+                <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=" height="100" widht="470" alt="chateau en foret1">
+                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
+                et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+            </divc>
+            <div id="projet_3">
+                <H3>projet 3</H3>
+                <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=" height="100" widht="470" alt="chateau en foret1">
+                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
+                et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+            </div>


cs

________________________________

In index.html<https://github.com/RozkeAdine/DonkeySchool/pull/2#discussion_r880427742>:

> +                <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=" height="100" widht="470" alt="chateau en foret1">
+                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
+                et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+            </div>
+            <divc id="projet_2">
+                <H3>projet 2</H3>
+                <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=" height="100" widht="470" alt="chateau en foret1">
+                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
+                et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+            </divc>
+            <div id="projet_3">
+                <H3>projet 3</H3>
+                <img src="https://media.istockphoto.com/photos/jardin-colombia-picture-id1385882999?k=20&m=1385882999&s=612x612&w=0&h=y5-y2n0V2hVqtG8zBWDn093mQYkQyBv8-r33EJ2vy4M=" height="100" widht="470" alt="chateau en foret1">
+                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis illo voluptate, molestias delectus quia,
+                et numquam repudiandae placeat quasi alias vel excepturi dignissimos tenetur dolor cum assumenda accusantium fugiat at.</p>
+            </div>
             </article>



nothing in there ?

________________________________

In index.html<https://github.com/RozkeAdine/DonkeySchool/pull/2#discussion_r880 [...]

2022-05-27 10:17 UTC, merged